-- Create locations table for Canada city/province autocomplete
-- Safe/idempotent, with indexes for fast search

CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL,
  province TEXT NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  population INTEGER,
  -- Precomputed field for fast fuzzy search
  search_text TEXT GENERATED ALWAYS AS (
    LOWER(REGEXP_REPLACE(city || ' ' || province, '\s+', ' ', 'g'))
  ) STORED
);

-- Basic uniqueness to avoid dup rows on bulk import (optional)
CREATE UNIQUE INDEX IF NOT EXISTS idx_locations_city_province_unique
  ON public.locations (LOWER(city), LOWER(province));

-- Trigram index for fast autocomplete (requires pg_trgm extension)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_locations_search_trgm
  ON public.locations USING GIN (search_text gin_trgm_ops);

-- Support exact province/city lookups and ordering
CREATE INDEX IF NOT EXISTS idx_locations_province_city
  ON public.locations (province, city);

CREATE INDEX IF NOT EXISTS idx_locations_population
  ON public.locations (population DESC NULLS LAST);

-- Example upsert (uncomment and modify to seed a few records)
-- INSERT INTO public.locations (city, province, lat, lng, population)
-- VALUES 
--   ('Toronto', 'Ontario', 43.65107, -79.347015, 2731571),
--   ('Montreal', 'Quebec', 45.50169, -73.567253, 1704694),
--   ('Vancouver', 'British Columbia', 49.28273, -123.120735, 631486)
-- ON CONFLICT (LOWER(city), LOWER(province)) DO UPDATE
-- SET lat = EXCLUDED.lat,
--     lng = EXCLUDED.lng,
--     population = EXCLUDED.population;

-- Usage pattern (client):
-- SELECT city, province, lat, lng
-- FROM public.locations
-- WHERE search_text ILIKE '%' || LOWER($1) || '%'
-- ORDER BY population DESC NULLS LAST
-- LIMIT 8;


